services:
  # Web Service
  - type: web
    name: trapick
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn trapick.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEPLOYMENT_ENV
        value: cloud
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: SYNC_API_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    
  # PostgreSQL Database
  - type: pgsql
    name: trapick-db
    plan: free
    databaseName: trapickdb
    user: trapickuser