# Generated by Django 4.2.23 on 2025-11-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingprofile',
            options={'ordering': ['road_type', 'display_name']},
        ),
        migrations.AddField(
            model_name='processingprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='processingprofile',
            name='config_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for this processing profile'),
        ),
        migrations.AlterField(
            model_name='processingprofile',
            name='detector_class',
            field=models.CharField(default='RTXVehicleDetector', help_text='Python class name of the detector to use', max_length=100),
        ),
        migrations.AlterField(
            model_name='processingprofile',
            name='detector_module',
            field=models.CharField(default='ml.vehicle_detector', help_text='Python module path where detector class is located', max_length=200),
        ),
        migrations.AlterField(
            model_name='processingprofile',
            name='road_type',
            field=models.CharField(choices=[('highway', 'Highway'), ('intersection', 'Intersection'), ('y_junction', 'Y-Junction'), ('t_intersection', 'T-Intersection'), ('roundabout', 'Roundabout'), ('urban', 'Urban Street'), ('generic', 'Generic'), ('custom', 'Custom')], default='generic', max_length=50),
        ),
    ]
