# Generated by Django 4.2.23 on 2025-10-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='processed_session_video_path',
            field=models.FileField(blank=True, null=True, upload_to='processed_session_videos/'),
        ),
    ]
