# Generated by Django 4.2.23 on 2025-11-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='last_progress_update',
            field=models.DateTimeField(auto_now=True, help_text='Last time progress was updated'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='processing_message',
            field=models.CharField(default='Waiting to start...', help_text='Current processing status message', max_length=255),
        ),
        migrations.AddField(
            model_name='videofile',
            name='processing_progress',
            field=models.IntegerField(default=0, help_text='Processing progress percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='videofile',
            index=models.Index(fields=['processing_status', 'processing_progress'], name='trapickapp__process_6ec5e9_idx'),
        ),
    ]
