# Generated by Django 4.2.23 on 2025-10-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficanalysis',
            name='average_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trafficanalysis',
            name='average_gap_seconds',
            field=models.FloatField(blank=True, help_text='Average time between vehicles in seconds', null=True),
        ),
        migrations.AddField(
            model_name='trafficanalysis',
            name='density_vehicles_per_km',
            field=models.FloatField(blank=True, help_text='Vehicle density per kilometer', null=True),
        ),
        migrations.AddField(
            model_name='trafficanalysis',
            name='detection_accuracy',
            field=models.FloatField(blank=True, help_text='Overall detection confidence score (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='trafficanalysis',
            name='detection_consistency',
            field=models.FloatField(blank=True, help_text='How consistent detections are across frames (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='trafficanalysis',
            name='frames_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trafficanalysis',
            name='hourly_breakdown',
            field=models.JSONField(default=dict, help_text="Vehicle counts by hour: {'0': {'car': 10, 'truck': 2}, '1': {'car': 15, 'truck': 3}}"),
        ),
        migrations.AddField(
            model_name='trafficanalysis',
            name='processing_quality_score',
            field=models.FloatField(blank=True, help_text='Overall quality score considering multiple factors', null=True),
        ),
        migrations.AddField(
            model_name='trafficanalysis',
            name='speed_analysis',
            field=models.JSONField(default=dict, help_text="Average speeds by vehicle type: {'car': 45.2, 'truck': 38.7}"),
        ),
        migrations.AddField(
            model_name='trafficanalysis',
            name='traffic_flow_rate',
            field=models.FloatField(blank=True, help_text='Vehicles per hour', null=True),
        ),
    ]
