# Generated by Django 4.2.23 on 2025-09-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='processed_video_path',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
    ]
