# Generated by Django 4.2.23 on 2025-09-08 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrafficSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_count', models.IntegerField()),
                ('peak_hour', models.IntegerField()),
                ('peak_hour_count', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('frame_number', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('bbox_x', models.FloatField()),
                ('bbox_y', models.FloatField()),
                ('bbox_width', models.FloatField()),
                ('bbox_height', models.FloatField()),
                ('track_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyTrafficSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('total_frames', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicledetection',
            name='video',
        ),
        migrations.RemoveField(
            model_name='trafficprediction',
            name='generated_at',
        ),
        migrations.AddField(
            model_name='trafficprediction',
            name='confidence_interval_lower',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trafficprediction',
            name='confidence_interval_upper',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trafficprediction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficprediction',
            name='model_version',
            field=models.CharField(default='v1', max_length=50),
        ),
        migrations.AlterField(
            model_name='trafficprediction',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trafficprediction',
            name='hour_of_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trafficprediction',
            name='predicted_congestion',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='TrafficAnalysis',
        ),
        migrations.DeleteModel(
            name='VehicleDetection',
        ),
        migrations.DeleteModel(
            name='VideoUpload',
        ),
        migrations.AddField(
            model_name='hourlytrafficsummary',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trapickapp.vehicletype'),
        ),
        migrations.AddField(
            model_name='detection',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trapickapp.location'),
        ),
        migrations.AddField(
            model_name='detection',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trapickapp.vehicletype'),
        ),
        migrations.AddField(
            model_name='detection',
            name='video_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='trapickapp.videofile'),
        ),
        migrations.AddField(
            model_name='dailytrafficsummary',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trapickapp.vehicletype'),
        ),
        migrations.AddIndex(
            model_name='hourlytrafficsummary',
            index=models.Index(fields=['date', 'hour'], name='trapickapp__date_ee26b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hourlytrafficsummary',
            unique_together={('date', 'hour', 'vehicle_type')},
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['timestamp'], name='trapickapp__timesta_20fc2c_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['vehicle_type', 'timestamp'], name='trapickapp__vehicle_80168d_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['location', 'timestamp'], name='trapickapp__locatio_411009_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytrafficsummary',
            unique_together={('date', 'vehicle_type')},
        ),
    ]
