# Generated by Django 4.2.23 on 2025-10-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0002_trafficanalysis_average_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='actual_datetime',
            field=models.DateTimeField(blank=True, help_text='Combined date and time from filename', null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='actual_recording_date',
            field=models.DateField(blank=True, help_text='Extracted from filename', null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='actual_start_time',
            field=models.TimeField(blank=True, help_text='Extracted from filename', null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='camera_id',
            field=models.CharField(blank=True, help_text='Extracted from filename (e.g., D11, D12)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='filename_parsed',
            field=models.BooleanField(default=False, help_text='Whether filename was successfully parsed'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='parsing_notes',
            field=models.TextField(blank=True, help_text='Notes about filename parsing results'),
        ),
    ]
