# Generated by Django 4.2.23 on 2025-10-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0002_analysissession_processed_session_video_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytrafficsummary',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='detection',
            options={'ordering': ['timestamp', 'frame_number']},
        ),
        migrations.AlterModelOptions(
            name='frameanalysis',
            options={'ordering': ['frame_number']},
        ),
        migrations.AlterModelOptions(
            name='hourlytrafficsummary',
            options={'ordering': ['date', 'hour']},
        ),
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='trafficanalysis',
            options={'ordering': ['-analyzed_at'], 'verbose_name_plural': 'Traffic Analyses'},
        ),
        migrations.AlterModelOptions(
            name='trafficprediction',
            options={'ordering': ['prediction_date', 'hour_of_day']},
        ),
        migrations.AlterModelOptions(
            name='trafficreport',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['display_name']},
        ),
        migrations.AlterModelOptions(
            name='videofile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='processed_session_video_path',
            field=models.FileField(blank=True, help_text='Processed video file for the entire analysis session', max_length=500, null=True, upload_to='processed_session_videos/'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('uploaded', 'Uploaded')], default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='analysissession',
            index=models.Index(fields=['status'], name='trapickapp__status_84cb24_idx'),
        ),
        migrations.AddIndex(
            model_name='analysissession',
            index=models.Index(fields=['location', 'created_at'], name='trapickapp__locatio_f0f5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['video_file', 'frame_number'], name='trapickapp__video_f_d9015f_idx'),
        ),
        migrations.AddIndex(
            model_name='videofile',
            index=models.Index(fields=['processing_status'], name='trapickapp__process_f0ae3a_idx'),
        ),
        migrations.AddIndex(
            model_name='videofile',
            index=models.Index(fields=['analysis_session', 'video_date'], name='trapickapp__analysi_e7a439_idx'),
        ),
        migrations.AddIndex(
            model_name='videofile',
            index=models.Index(fields=['video_date', 'video_start_time'], name='trapickapp__video_d_122e5b_idx'),
        ),
    ]
