# Generated by Django 4.2.23 on 2026-02-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0003_processingprofile_config_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
