# Generated by Django 4.2.23 on 2026-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0004_alter_videofile_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdategroup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
