# Generated by Django 4.2.23 on 2025-11-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0004_analysissession_auto_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissession',
            name='auto_created',
        ),
        migrations.RemoveField(
            model_name='analysissession',
            name='created_by',
        ),
    ]
