# Generated by Django 4.2.23 on 2026-02-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0005_locationdategroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingprofile',
            name='detector_type',
            field=models.CharField(choices=[('vertical_top_bottom', 'Vertical Top→Bottom'), ('vertical_bottom_top', 'Vertical Bottom→Top'), ('horizontal_left_right', 'Horizontal Left→Right'), ('horizontal_right_left', 'Horizontal Right→Left'), ('diagonal_ne_sw', 'Diagonal NE→SW'), ('diagonal_nw_se', 'Diagonal NW→SE'), ('diagonal_se_nw', 'Diagonal SE→NW'), ('diagonal_sw_ne', 'Diagonal SW→NE')], default='vertical_top_bottom', help_text='Type of detector to use', max_length=50),
        ),
    ]
