# Generated by Django 4.2.23 on 2026-02-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0006_alter_processingprofile_detector_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdategroup',
            name='coverage_continuity_score',
            field=models.FloatField(default=100.0, help_text='Percentage of continuous coverage (0-100)'),
        ),
        migrations.AddField(
            model_name='locationdategroup',
            name='coverage_gaps',
            field=models.JSONField(blank=True, default=list, help_text='List of time gaps between videos'),
        ),
        migrations.AddField(
            model_name='locationdategroup',
            name='coverage_segments',
            field=models.JSONField(blank=True, default=list, help_text='List of video segments with their time ranges'),
        ),
        migrations.AddField(
            model_name='locationdategroup',
            name='hourly_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='Hourly vehicle distribution across all videos'),
        ),
        migrations.AddField(
            model_name='locationdategroup',
            name='total_coverage_minutes',
            field=models.FloatField(default=0.0, help_text='Total minutes of video coverage'),
        ),
    ]
