# Generated by Django 4.2.23 on 2026-02-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0007_locationdategroup_coverage_continuity_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytrafficsummary',
            name='directional_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detection',
            name='counted_directionally',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detection',
            name='direction_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directionalanalysis',
            name='direction_angle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='directionalanalysis',
            name='direction_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='frameanalysis',
            name='directional_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hourlytrafficsummary',
            name='directional_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locationdategroup',
            name='average_directional_flow',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='locationdategroup',
            name='coverage_continuity_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='locationdategroup',
            name='coverage_gaps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='locationdategroup',
            name='coverage_segments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='locationdategroup',
            name='hourly_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='locationdategroup',
            name='peak_directional_flow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locationdategroup',
            name='total_coverage_minutes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='locationdategroup',
            name='total_directional_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='congestion_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='congestion_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='congestion_heavy_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='congestion_light_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='congestion_moderate_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='congestion_none_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='congestion_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='congestion_severe_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='directional_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='directional_vehicles_per_minute',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='duration_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='fps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='frame_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='peak_directional_flow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='total_congestion_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trafficanalysis',
            name='total_frames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trafficprediction',
            name='predicted_directional_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='last_progress_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='original_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='processing_message',
            field=models.CharField(default='Waiting to start...', max_length=255),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='processing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trapickapp.processingprofile'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='processing_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='video_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='video_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='video_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
